<?php


namespace HighlightLib\Token;


use HighlightLib\Contracts\TokenInterface;

class NewLine extends AbstractToken
{
    /**
     * @return string
     */
    public function getCSSType(): string
    {
        // TODO: Implement getCSSType() method.
        return '';
    }

    /**
     * @return string
     */
    public function getCSS(): string
    {
        return '</br>'; // TODO: Change the autogenerated stub
    }
}